### ISSUE TITLE
Implement Line drawing

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/hexameter#18]
http://www.redblobgames.com/grids/hexagons/#line-drawing

**Comment by pubudug** [comment]
Hi Adam, I would like to work on this issue. I am following http://www.redblobgames.com/grids/hexagons/#line-drawing with the intention of attempting it.

**Comment by adam-arold** [comment]
Hi pubudug. It should be compatible with java 1.7. I've backported the whole library because it needs to work on Android and they don't have java 1.8 yet. You might want to peruse the source code, the .pom files and the checkstyle/findbugz settings to get a hang of the code style. I can give you the formatter config I use (IDEA). I'll soon add an .md detailing the COC. Have fun, and feel free to ask if something is unclear!
