### ISSUE TITLE
Use standard Open Source license

### ISSUE THREAD

**Issue by drekbour** [Hexworks/hexameter#40]
Bespoke licenses force developers to pause and become trainee lawers before progressing. Given the apparent free-for-all nature of Hexameter LICENSE file, why not just use BSD2?

https://opensource.org/licenses/BSD-3-Clause

**Comment by adam-arold** [comment]
Hexameter uses the MIT license which is pretty much standard. Did I miss something?

**Comment by drekbour** [comment]
Aha, so what I'm complaining about is that the MIT license doesn't declare itself to be the MIT license like, say, Apache license!

**Comment by adam-arold** [comment]
I'm not sure I follow. GitHub seems to recognize it: 
![image](https://user-images.githubusercontent.com/1253248/46259892-5bb2dd80-c4df-11e8-9879-dca9e00310d6.png) and it is also one of the recommended licenses by GitHub (take a look [here](https://github.com/github/choosealicense.com)). Can you clarify your point?

**Comment by drekbour** [comment]
Aw, I don't look at Github to tell me stuff like that, I cloned and perused the codebase but I didn't pay recognise the MIT format. No issue here 'cept with me! Will send some PRs your way shortly for minor items and raise some Issues for other stuff.

**Comment by adam-arold** [comment]
That's **great news**! Feel free to come up to our [discord server](https://discord.gg/hQnNxd) if you'd want to discuss things. We have plans to change the *MIT* license to *Apache* though but it is also well-explained and recognized by GitHub.
